### ISSUE TITLE
Cannot load YAML

### ISSUE THREAD

**Issue by ianchov** [banstola/WebSmser#1]
PHP message: PHP Fatal error:  require_once(): Failed opening required './Symfony\Component\Yaml\Yaml.php' (include_path='.:/usr/share/php:) in /var/www/sites/twillioSMS/WebSmser/src/DemoSend.php on line 7" while reading response header from upstream, client: 77.85.34.145, server: stamps.bg, request: "POST /twilliosms/src/DemoSend.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "stamps.bg", referrer: "https://DOMAINHERE/twilliosms/web/index.html"

**Comment by banstola** [comment]
Did you read the instruction properly? It seems you did not run composer install at least
